############################
## CHANGE THESE
############################

baseURL: 'https://AlexanderHenkel.github.io/qubt'
title: qubt

############################
## MISC
############################

enableEmoji: true
disableKinds: ['taxonomy', 'term']
languageCode: 'en-us'


